### ISSUE TITLE
a question about protein predict

### ISSUE THREAD

**Issue by CNwangbin** [bio-ontology-research-group/deepgozero#4]
why do predict by two vectors inner product plus a scalar，I could not fully understand the formular.
![image](https://user-images.githubusercontent.com/87804802/169651765-25fbc044-269e-49ab-b6a0-9ed06e05d76d.png)

**Comment by coolmaksat** [comment]
Hi,
Vectors represent protein and center point of an n-ball and scalar is a radius of an n-ball of GO class. The inner product accounts for the similarity of the vectors and the radius is larger for general classes and small for specific classes. Let me know if this helps.

**Comment by CNwangbin** [comment]
ok, thanks for your reply.
