### ISSUE TITLE
A question about the 'go.norm' file.

### ISSUE THREAD

**Issue by CNwangbin** [bio-ontology-research-group/deepgozero#5]
My question is I don't know how to extract the 'go.norm' file from 'go.owl'. I'm not familiar about Ontology Language and groovy script language. In my conception, the files 'Normalizer.groovy', 'Corpus.groovy' and 'Axioms.groovy' were used to extract NF1~NF4 from go.owl file.And I don't know the data flow excatlly pass. I hope you could explain the data flow for me(the best way with a graph).Thanks for you very much.

**Comment by coolmaksat** [comment]
Hi,
use Normalizer.groovy to generate go.norm file, you need to provide an owl file.
