### ISSUE TITLE
Calculate AUC

### ISSUE THREAD

**Issue by Worldseer** [bio-ontology-research-group/deepgozero#9]
Hello Dr. Kulmanov，
Did DeepGOZero do propagation when evaluating AUC? I see that lines 156-177 in [deepgozero.py](https://github.com/bio-ontology-research-group/deepgozero/blob/main/deepgozero.py#L156) calculate the AUC first and then do propagation.
thanks, wish you all the best

**Comment by coolmaksat** [comment]
Hi,
The AUC you are referring to is a micro AUC and calculated before propagation. We monitor micro AUC during the training to see if we are getting any prediction signal. This measure is not used for selecting the model or reporting the performance. We report term-centric (macro) AUC which is calculated after the propagation. (see evaluate_terms.py script)
Thank you.

**Comment by Worldseer** [comment]
Thank you.
